overrides:
  rollup: 4.59.0
  minimatch: 9.0.7
  serialize-javascript: 7.0.3
  ajv: 6.14.0

allowedDeprecatedVersions:
  glob: '*'
  source-map: 0.8.0-beta.0
  sourcemap-codec: '*'

allowBuilds:
  esbuild: true
