/**
 * Particles Presets for the Kwami AI Playground
 *
 * Visual presets for the particles avatar renderer.
 * Uses the new section-based particles state structure.
 */

import type { ParticlesState } from '../stores/avatar.particles';

export interface ParticlesPreset {
  id: string;
  name: string;
  icon: string;
  particles: Partial<ParticlesState>;
}

export const particlesPresetsData: ParticlesPreset[] = [
  {
    id: 'particles-default',
    name: 'Default',
    icon: 'ph:circles-three-duotone',
    particles: {
      formation: {
        type: 'sphere',
        radius: 2,
        density: 'uniform',
        noise: 0.03,
      },
      visual: {
        color: '#ffffff',
        glowColor: '#88ccff',
        particleSize: 0.6,
        sizeVariation: 0.5,
        opacity: 0.95,
        glowIntensity: 0.3,
        brightnessVariation: 0.25,
        sharpness: 0.7,
      },
      transform: {
        scale: 1,
        particleCount: 6000,
      },
      physics: {
        returnForce: 0.04,
        damping: 0.92,
        explosionForce: 10,
        explosionRadius: 2.5,
        leaderSpeed: 0.015,
        followDelay: 0.012,
        mouseInfluence: 1.5,
        mouseRepulsion: 0.4,
      },
      animation: {
        enabled: true,
        breathing: { enabled: true, speed: 1.0, intensity: 0.15 },
        floating: { enabled: true, speed: 0.5, amplitude: 0.08 },
        rotation: { enabled: true, speedX: 0, speedY: 0.1, speedZ: 0 },
        wave: { enabled: false, speed: 1.5, amplitude: 0.1 },
        turbulence: { enabled: true, intensity: 0.02, speed: 1.0 },
      },
      audio: {
        enabled: true,
        reactivity: 1.5,
        smoothing: 0.7,
        scalePulse: true,
        movementIntensity: 0.5,
        frequencyInfluence: { bass: 1.0, mid: 0.6, high: 0.8 },
      },
    },
  },
  {
    id: 'particles-dense',
    name: 'Dense',
    icon: 'ph:dots-nine-duotone',
    particles: {
      formation: {
        type: 'sphere',
        radius: 2,
        density: 'center-heavy',
        noise: 0.02,
      },
      visual: {
        color: '#ffffff',
        glowColor: '#aaddff',
        particleSize: 1.8,
        sizeVariation: 0.3,
        opacity: 0.85,
        glowIntensity: 0.4,
        brightnessVariation: 0.2,
        sharpness: 0.8,
      },
      transform: {
        scale: 1,
        particleCount: 15000,
      },
      physics: {
        returnForce: 0.05,
        damping: 0.9,
        explosionForce: 8,
        explosionRadius: 2.0,
        leaderSpeed: 0.012,
        followDelay: 0.01,
        mouseInfluence: 1.2,
        mouseRepulsion: 0.3,
      },
      animation: {
        enabled: true,
        breathing: { enabled: true, speed: 0.8, intensity: 0.1 },
        floating: { enabled: true, speed: 0.4, amplitude: 0.05 },
        rotation: { enabled: true, speedX: 0, speedY: 0.08, speedZ: 0 },
        wave: { enabled: false, speed: 1.0, amplitude: 0.08 },
        turbulence: { enabled: true, intensity: 0.015, speed: 0.8 },
      },
      audio: {
        enabled: true,
        reactivity: 1.3,
        smoothing: 0.75,
        scalePulse: true,
        movementIntensity: 0.4,
        frequencyInfluence: { bass: 0.8, mid: 0.5, high: 0.6 },
      },
    },
  },
  {
    id: 'particles-sparse',
    name: 'Sparse',
    icon: 'ph:dots-three-duotone',
    particles: {
      formation: {
        type: 'sphere',
        radius: 2.5,
        density: 'edge-heavy',
        noise: 0.05,
      },
      visual: {
        color: '#ffffff',
        glowColor: '#ffcc88',
        particleSize: 3.5,
        sizeVariation: 0.6,
        opacity: 0.9,
        glowIntensity: 0.5,
        brightnessVariation: 0.5,
        sharpness: 0.6,
      },
      transform: {
        scale: 1,
        particleCount: 3000,
      },
      physics: {
        returnForce: 0.03,
        damping: 0.94,
        explosionForce: 12,
        explosionRadius: 3.0,
        leaderSpeed: 0.02,
        followDelay: 0.015,
        mouseInfluence: 2.0,
        mouseRepulsion: 0.5,
      },
      animation: {
        enabled: true,
        breathing: { enabled: true, speed: 1.2, intensity: 0.2 },
        floating: { enabled: true, speed: 0.6, amplitude: 0.12 },
        rotation: { enabled: true, speedX: 0, speedY: 0.15, speedZ: 0 },
        wave: { enabled: true, speed: 2.0, amplitude: 0.15 },
        turbulence: { enabled: true, intensity: 0.03, speed: 1.2 },
      },
      audio: {
        enabled: true,
        reactivity: 1.8,
        smoothing: 0.6,
        scalePulse: true,
        movementIntensity: 0.7,
        frequencyInfluence: { bass: 1.2, mid: 0.7, high: 1.0 },
      },
    },
  },
  {
    id: 'particles-reactive',
    name: 'Reactive',
    icon: 'ph:waveform-duotone',
    particles: {
      formation: {
        type: 'sphere',
        radius: 2,
        density: 'uniform',
        noise: 0.04,
      },
      visual: {
        color: '#ff6699',
        glowColor: '#ff99cc',
        particleSize: 2.0,
        sizeVariation: 0.4,
        opacity: 0.95,
        glowIntensity: 0.6,
        brightnessVariation: 0.3,
        sharpness: 0.75,
      },
      transform: {
        scale: 1,
        particleCount: 8000,
      },
      physics: {
        returnForce: 0.05,
        damping: 0.88,
        explosionForce: 12,
        explosionRadius: 2.5,
        leaderSpeed: 0.02,
        followDelay: 0.008,
        mouseInfluence: 1.8,
        mouseRepulsion: 0.6,
      },
      animation: {
        enabled: true,
        breathing: { enabled: true, speed: 1.5, intensity: 0.25 },
        floating: { enabled: true, speed: 0.8, amplitude: 0.1 },
        rotation: { enabled: true, speedX: 0.05, speedY: 0.12, speedZ: 0.03 },
        wave: { enabled: true, speed: 2.5, amplitude: 0.12 },
        turbulence: { enabled: true, intensity: 0.04, speed: 1.5 },
      },
      audio: {
        enabled: true,
        reactivity: 2.5,
        smoothing: 0.5,
        scalePulse: true,
        movementIntensity: 0.9,
        frequencyInfluence: { bass: 1.5, mid: 1.0, high: 1.2 },
      },
    },
  },
  {
    id: 'particles-calm',
    name: 'Calm',
    icon: 'ph:moon-duotone',
    particles: {
      formation: {
        type: 'sphere',
        radius: 2.2,
        density: 'uniform',
        noise: 0.02,
      },
      visual: {
        color: '#aaccff',
        glowColor: '#6699cc',
        particleSize: 1.5,
        sizeVariation: 0.3,
        opacity: 0.8,
        glowIntensity: 0.25,
        brightnessVariation: 0.15,
        sharpness: 0.65,
      },
      transform: {
        scale: 1,
        particleCount: 5000,
      },
      physics: {
        returnForce: 0.015,
        damping: 0.96,
        explosionForce: 5,
        explosionRadius: 2.0,
        leaderSpeed: 0.01,
        followDelay: 0.02,
        mouseInfluence: 0.8,
        mouseRepulsion: 0.2,
      },
      animation: {
        enabled: true,
        breathing: { enabled: true, speed: 0.5, intensity: 0.08 },
        floating: { enabled: true, speed: 0.3, amplitude: 0.04 },
        rotation: { enabled: true, speedX: 0, speedY: 0.05, speedZ: 0 },
        wave: { enabled: false, speed: 1.0, amplitude: 0.05 },
        turbulence: { enabled: true, intensity: 0.01, speed: 0.5 },
      },
      audio: {
        enabled: true,
        reactivity: 0.5,
        smoothing: 0.9,
        scalePulse: false,
        movementIntensity: 0.2,
        frequencyInfluence: { bass: 0.3, mid: 0.2, high: 0.4 },
      },
    },
  },
  {
    id: 'particles-disc',
    name: 'Disc',
    icon: 'ph:circle-duotone',
    particles: {
      formation: {
        type: 'disc',
        radius: 2.5,
        density: 'uniform',
        noise: 0.03,
      },
      visual: {
        color: '#ffdd44',
        glowColor: '#ffaa00',
        particleSize: 2.2,
        sizeVariation: 0.5,
        opacity: 0.92,
        glowIntensity: 0.45,
        brightnessVariation: 0.35,
        sharpness: 0.7,
      },
      transform: {
        scale: 1,
        particleCount: 7000,
      },
      physics: {
        returnForce: 0.04,
        damping: 0.91,
        explosionForce: 10,
        explosionRadius: 2.5,
        leaderSpeed: 0.015,
        followDelay: 0.012,
        mouseInfluence: 1.5,
        mouseRepulsion: 0.4,
      },
      animation: {
        enabled: true,
        breathing: { enabled: true, speed: 0.9, intensity: 0.12 },
        floating: { enabled: false, speed: 0.5, amplitude: 0.08 },
        rotation: { enabled: true, speedX: 0, speedY: 0.2, speedZ: 0 },
        wave: { enabled: true, speed: 1.8, amplitude: 0.08 },
        turbulence: { enabled: true, intensity: 0.02, speed: 1.0 },
      },
      audio: {
        enabled: true,
        reactivity: 1.6,
        smoothing: 0.65,
        scalePulse: true,
        movementIntensity: 0.55,
        frequencyInfluence: { bass: 1.1, mid: 0.7, high: 0.9 },
      },
    },
  },
  {
    id: 'particles-ring',
    name: 'Ring',
    icon: 'ph:circle-dashed-duotone',
    particles: {
      formation: {
        type: 'ring',
        radius: 2,
        density: 'uniform',
        noise: 0.02,
      },
      visual: {
        color: '#66ffcc',
        glowColor: '#33cc99',
        particleSize: 2.5,
        sizeVariation: 0.4,
        opacity: 0.9,
        glowIntensity: 0.5,
        brightnessVariation: 0.3,
        sharpness: 0.75,
      },
      transform: {
        scale: 1,
        particleCount: 4000,
      },
      physics: {
        returnForce: 0.035,
        damping: 0.93,
        explosionForce: 8,
        explosionRadius: 2.0,
        leaderSpeed: 0.018,
        followDelay: 0.01,
        mouseInfluence: 1.3,
        mouseRepulsion: 0.35,
      },
      animation: {
        enabled: true,
        breathing: { enabled: true, speed: 1.0, intensity: 0.15 },
        floating: { enabled: true, speed: 0.4, amplitude: 0.06 },
        rotation: { enabled: true, speedX: 0, speedY: 0.25, speedZ: 0.1 },
        wave: { enabled: false, speed: 1.5, amplitude: 0.1 },
        turbulence: { enabled: true, intensity: 0.018, speed: 0.9 },
      },
      audio: {
        enabled: true,
        reactivity: 1.4,
        smoothing: 0.7,
        scalePulse: true,
        movementIntensity: 0.5,
        frequencyInfluence: { bass: 0.9, mid: 0.6, high: 0.75 },
      },
    },
  },
  {
    id: 'particles-cube',
    name: 'Cube',
    icon: 'ph:cube-duotone',
    particles: {
      formation: {
        type: 'cube',
        radius: 1.8,
        density: 'uniform',
        noise: 0.01,
      },
      visual: {
        color: '#cc88ff',
        glowColor: '#9944ff',
        particleSize: 1.8,
        sizeVariation: 0.2,
        opacity: 0.95,
        glowIntensity: 0.4,
        brightnessVariation: 0.2,
        sharpness: 0.85,
      },
      transform: {
        scale: 1,
        particleCount: 6000,
      },
      physics: {
        returnForce: 0.06,
        damping: 0.89,
        explosionForce: 15,
        explosionRadius: 2.0,
        leaderSpeed: 0.02,
        followDelay: 0.008,
        mouseInfluence: 1.6,
        mouseRepulsion: 0.5,
      },
      animation: {
        enabled: true,
        breathing: { enabled: false, speed: 1.0, intensity: 0.15 },
        floating: { enabled: false, speed: 0.5, amplitude: 0.08 },
        rotation: { enabled: true, speedX: 0.08, speedY: 0.08, speedZ: 0.08 },
        wave: { enabled: false, speed: 1.5, amplitude: 0.1 },
        turbulence: { enabled: true, intensity: 0.01, speed: 0.7 },
      },
      audio: {
        enabled: true,
        reactivity: 1.7,
        smoothing: 0.6,
        scalePulse: true,
        movementIntensity: 0.6,
        frequencyInfluence: { bass: 1.0, mid: 0.8, high: 0.9 },
      },
    },
  },
];
